### PR TITLE
Improve type generation in empty types

### PR DESCRIPTION
**Pull request by ivanpajon**
In case we have Auth Collections without aditional fields, generated types shows an error:
image

Also for empty relations:
image

This Pull Request improves that by implementing `Record<string, never>`.
image
image

### CODE REVIEW

**Comment by david-plugge** [comment]
Interesting, I haven't encountered that myself, maybe it depends on the tsconfig.
I'm in the process of refactoring the code and I think it's better to use interfaces rather than types which should also solve this issue.

**Comment by david-plugge** [comment]
Thank you very much for this PR, i've made some changes in the current branch so interfaces are used instead of types and `Record<string, never>` instead of empty objects.

Let me know if i missed something or if we can close this PR.

**Comment by ivanpajon** [comment]
I like the changes you have made. I update the PR to (imo) improve the legibility of empty types.

Before (notice the blank lines):
before

After:
after

**Comment by david-plugge** [comment]
I see, that looks better!
There is a conflict now after merging another PR, could you resolve that? ty!

**Comment by ivanpajon** [comment]
Solved!

**Pull request merged**
